"""Weekly editorial digest — one paragraph of human-readable narrative
covering both tours for a given Monday-anchored week.

Stored once, served from cache (no per-request LLM call). Generated by
the cron job in `app/jobs/scheduler.py` and the backfill script in
`scripts/backfill_digests.py`, both of which call into
`app/services/editorial_digest.py`.
"""

from datetime import date, datetime

from sqlmodel import Field, SQLModel


class EditorialDigest(SQLModel, table=True):
    __tablename__ = "editorial_digests"

    id: int | None = Field(default=None, primary_key=True)

    # ISO Monday for the week being summarised. Unique so re-runs are
    # idempotent — the service skips a week that already has a row
    # unless `force=True`.
    week_start: date = Field(index=True, unique=True)

    headline: str
    body_md: str

    # JSON-serialised dump of the structured facts we fed the model.
    # Kept for audit and for re-runs against an updated prompt without
    # re-querying the DB.
    source_json: str

    # JSON-serialised list of Google Ads campaign briefs produced
    # alongside the digest. Each entry has a theme, keyword list, ad
    # headlines, descriptions, and a landing URL on mob.tennis.
    # Surfaced on /admin/campaigns/<week> for the human operator to
    # copy-paste into Google Ads UI. Null on backfilled digests that
    # predate this feature.
    campaign_briefs_json: str | None = None

    # Provider model id at time of generation. Useful when we eventually
    # swap models — old rows stay attributable to the model that wrote
    # them.
    model_name: str

    generated_at: datetime = Field(default_factory=datetime.utcnow)
