export const metadata = {
  title: "Editorial standards",
  description:
    "How Mobtennis sources its data, generates its prose, and corrects mistakes.",
};

export default function StandardsPage() {
  return (
    <article className="space-y-6 pt-2">
      <header>
        <h1 className="text-2xl font-bold tracking-tight">Editorial standards</h1>
        <p className="mt-1 text-sm text-text-secondary">
          Where the data comes from, how the prose gets written, and what to do
          when we&apos;ve got something wrong.
        </p>
      </header>

      <section className="space-y-2">
        <h2 className="text-lg font-semibold">Where the data comes from</h2>
        <p className="text-sm text-text-secondary">
          Mobtennis is built on three sources, each with a specific role:
        </p>
        <ul className="ml-5 list-disc space-y-1 text-sm text-text-secondary">
          <li>
            <strong>Live scores, schedules, and tournament metadata</strong> —{" "}
            <a
              href="https://api-tennis.com"
              target="_blank"
              rel="noopener noreferrer"
              className="text-accent underline decoration-dotted underline-offset-4 hover:text-accent-dim"
            >
              api-tennis.com
            </a>
            . A paid feed, polled and streamed for real-time updates.
          </li>
          <li>
            <strong>Historical match data, player records, and rankings</strong>{" "}
            — Jeff Sackmann&apos;s open{" "}
            <a
              href="https://github.com/JeffSackmann/tennis_atp"
              target="_blank"
              rel="noopener noreferrer"
              className="text-accent underline decoration-dotted underline-offset-4 hover:text-accent-dim"
            >
              tennis_atp
            </a>{" "}
            and{" "}
            <a
              href="https://github.com/JeffSackmann/tennis_wta"
              target="_blank"
              rel="noopener noreferrer"
              className="text-accent underline decoration-dotted underline-offset-4 hover:text-accent-dim"
            >
              tennis_wta
            </a>{" "}
            CSV repositories. The canonical reference for tour history.
          </li>
          <li>
            <strong>Tournament draw structure, player bios, tournament blurbs</strong>{" "}
            — Wikipedia. Bracket pages are parsed nightly for ongoing top-tier
            events; biographies and tournament summaries come from Wikipedia
            articles and Wikidata.
          </li>
          <li>
            <strong>News and video highlights</strong> — public RSS feeds and
            the YouTube Data API, ingested every few minutes and matched to
            players and tournaments by name.
          </li>
        </ul>
      </section>

      <section className="space-y-2">
        <h2 className="text-lg font-semibold">How the prose is written</h2>
        <p className="text-sm text-text-secondary">
          The vast majority of the writing on this site is{" "}
          <strong>templated, not generated by an AI</strong>. Editorial
          paragraphs on head-to-head pages, player snapshots, tournament
          summaries, and match previews/recaps are composed from the underlying
          data using a small library of sentence variants chosen
          deterministically by the page&apos;s identifier — so the same page
          always reads the same way on every visit, while two similar pages
          don&apos;t read identical.
        </p>
        <p className="text-sm text-text-secondary">
          The one exception is the{" "}
          <strong>weekly editorial digest</strong>, which is generated by{" "}
          Claude Haiku once per week from a tightly-scoped fact sheet (the
          finals played, the notable upsets, the headline events still in
          progress). The model is instructed never to invent matches, scores,
          or players, and is constrained to a structured response format.
          Every digest is reviewable in the archive at{" "}
          <a
            href="/digest"
            className="text-accent underline decoration-dotted underline-offset-4 hover:text-accent-dim"
          >
            /digest
          </a>
          .
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-lg font-semibold">Accuracy and corrections</h2>
        <p className="text-sm text-text-secondary">
          Scores, draws, and rankings are updated automatically from the feeds
          above. Live scoring can lag the broadcast by 10–30 seconds, and
          third-party feeds occasionally publish errors that propagate to the
          site before we catch them. Bracket reconciliation between providers
          (Wikipedia&apos;s draw vs. api-tennis&apos;s live results) sometimes
          produces a stale row for a few minutes before the live consumer
          adopts it.
        </p>
        <p className="text-sm text-text-secondary">
          When you spot something wrong — a wrong score, a wrong winner, a
          player on the wrong side of the draw, prose that&apos;s clearly off
          — open an issue on{" "}
          <a
            href="https://github.com/mobtennis/mobtennis/issues"
            target="_blank"
            rel="noopener noreferrer"
            className="text-accent underline decoration-dotted underline-offset-4 hover:text-accent-dim"
          >
            GitHub
          </a>
          . A URL and a one-line description is plenty. We don&apos;t silently
          patch — when historical data changes, the change is in the public
          commit log.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-lg font-semibold">Independence</h2>
        <p className="text-sm text-text-secondary">
          Mobtennis isn&apos;t affiliated with the ATP, the WTA, the ITF, or
          any individual tournament. We don&apos;t accept paid placements,
          sponsored coverage, or affiliate partnerships that would steer
          editorial choices. Advertising on the site is run through
          arm&apos;s-length networks (currently{" "}
          <a
            href="/privacy#ads"
            className="text-accent underline decoration-dotted underline-offset-4 hover:text-accent-dim"
          >
            documented in our privacy policy
          </a>
          ); ad sales have no input into what the site says about a player,
          tournament, or result.
        </p>
        <p className="text-sm text-text-secondary">
          Profits, after hosting costs, are routed to the Tennis Association
          of Iceland for junior development — see{" "}
          <a
            href="/about"
            className="text-accent underline decoration-dotted underline-offset-4 hover:text-accent-dim"
          >
            About
          </a>{" "}
          for the full arrangement.
        </p>
      </section>
    </article>
  );
}
